################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../testsuite/single/tests/efuns/add_action.c \
../testsuite/single/tests/efuns/add_light.c \
../testsuite/single/tests/efuns/all_inventory.c \
../testsuite/single/tests/efuns/allocate.c \
../testsuite/single/tests/efuns/allocate_buffer.c \
../testsuite/single/tests/efuns/allocate_mapping.c \
../testsuite/single/tests/efuns/badshad.c \
../testsuite/single/tests/efuns/bind.c \
../testsuite/single/tests/efuns/break_string.c \
../testsuite/single/tests/efuns/cache_stats.c \
../testsuite/single/tests/efuns/call_other.c \
../testsuite/single/tests/efuns/call_out.c \
../testsuite/single/tests/efuns/call_stack.c \
../testsuite/single/tests/efuns/capitalize.c \
../testsuite/single/tests/efuns/children.c \
../testsuite/single/tests/efuns/clear_bit.c \
../testsuite/single/tests/efuns/clone_object.c \
../testsuite/single/tests/efuns/clonep.c \
../testsuite/single/tests/efuns/command.c \
../testsuite/single/tests/efuns/cp.c \
../testsuite/single/tests/efuns/crc32.c \
../testsuite/single/tests/efuns/ctime.c \
../testsuite/single/tests/efuns/deep_inherit_list.c \
../testsuite/single/tests/efuns/deep_inventory.c \
../testsuite/single/tests/efuns/destruct.c \
../testsuite/single/tests/efuns/disable_commands.c \
../testsuite/single/tests/efuns/dumpallobj.c \
../testsuite/single/tests/efuns/ed.c \
../testsuite/single/tests/efuns/enable_wizard.c \
../testsuite/single/tests/efuns/environment.c \
../testsuite/single/tests/efuns/error.c \
../testsuite/single/tests/efuns/exec.c \
../testsuite/single/tests/efuns/explode.c \
../testsuite/single/tests/efuns/file_name.c \
../testsuite/single/tests/efuns/file_size.c \
../testsuite/single/tests/efuns/filter.c \
../testsuite/single/tests/efuns/find_call_out.c \
../testsuite/single/tests/efuns/find_living.c \
../testsuite/single/tests/efuns/find_object.c \
../testsuite/single/tests/efuns/find_player.c \
../testsuite/single/tests/efuns/function_exists.c \
../testsuite/single/tests/efuns/function_profile.c \
../testsuite/single/tests/efuns/functionp.c \
../testsuite/single/tests/efuns/generate_source.c \
../testsuite/single/tests/efuns/get_char.c \
../testsuite/single/tests/efuns/get_config.c \
../testsuite/single/tests/efuns/get_dir.c \
../testsuite/single/tests/efuns/goodshad.c \
../testsuite/single/tests/efuns/has_errors.c \
../testsuite/single/tests/efuns/implode.c \
../testsuite/single/tests/efuns/in_edit.c \
../testsuite/single/tests/efuns/inh0.c \
../testsuite/single/tests/efuns/inh1.c \
../testsuite/single/tests/efuns/inh2.c \
../testsuite/single/tests/efuns/inherit_list.c \
../testsuite/single/tests/efuns/inherits.c \
../testsuite/single/tests/efuns/input_to.c \
../testsuite/single/tests/efuns/interactive.c \
../testsuite/single/tests/efuns/intp.c \
../testsuite/single/tests/efuns/keys.c \
../testsuite/single/tests/efuns/light.c \
../testsuite/single/tests/efuns/living.c \
../testsuite/single/tests/efuns/livings.c \
../testsuite/single/tests/efuns/lower_case.c \
../testsuite/single/tests/efuns/malloc_status.c \
../testsuite/single/tests/efuns/map.c \
../testsuite/single/tests/efuns/map_delete.c \
../testsuite/single/tests/efuns/mapp.c \
../testsuite/single/tests/efuns/master.c \
../testsuite/single/tests/efuns/match_path.c \
../testsuite/single/tests/efuns/member_array.c \
../testsuite/single/tests/efuns/message.c \
../testsuite/single/tests/efuns/mkdir.c \
../testsuite/single/tests/efuns/move_object.c \
../testsuite/single/tests/efuns/mud_status.c \
../testsuite/single/tests/efuns/notify_fail.c \
../testsuite/single/tests/efuns/nullp.c \
../testsuite/single/tests/efuns/objectp.c \
../testsuite/single/tests/efuns/opcprof.c \
../testsuite/single/tests/efuns/origin.c \
../testsuite/single/tests/efuns/pointerp.c \
../testsuite/single/tests/efuns/present.c \
../testsuite/single/tests/efuns/previous_object.c \
../testsuite/single/tests/efuns/printf.c \
../testsuite/single/tests/efuns/query_ed_mode.c \
../testsuite/single/tests/efuns/query_idle.c \
../testsuite/single/tests/efuns/query_ip_name.c \
../testsuite/single/tests/efuns/query_ip_number.c \
../testsuite/single/tests/efuns/query_load_average.c \
../testsuite/single/tests/efuns/query_privs.c \
../testsuite/single/tests/efuns/query_snoop.c \
../testsuite/single/tests/efuns/query_snooping.c \
../testsuite/single/tests/efuns/query_verb.c \
../testsuite/single/tests/efuns/random.c \
../testsuite/single/tests/efuns/read_buffer.c \
../testsuite/single/tests/efuns/read_bytes.c \
../testsuite/single/tests/efuns/read_file.c \
../testsuite/single/tests/efuns/receive.c \
../testsuite/single/tests/efuns/reg_assoc.c \
../testsuite/single/tests/efuns/regexp.c \
../testsuite/single/tests/efuns/remove_action.c \
../testsuite/single/tests/efuns/remove_call_out.c \
../testsuite/single/tests/efuns/rename.c \
../testsuite/single/tests/efuns/replace_string.c \
../testsuite/single/tests/efuns/restore_object.c \
../testsuite/single/tests/efuns/restore_variable.c \
../testsuite/single/tests/efuns/rm.c \
../testsuite/single/tests/efuns/rmdir.c \
../testsuite/single/tests/efuns/save_object.c \
../testsuite/single/tests/efuns/save_variable.c \
../testsuite/single/tests/efuns/say.c \
../testsuite/single/tests/efuns/set_bit.c \
../testsuite/single/tests/efuns/set_debug_level.c \
../testsuite/single/tests/efuns/set_heart_beat.c \
../testsuite/single/tests/efuns/set_hide.c \
../testsuite/single/tests/efuns/set_light.c \
../testsuite/single/tests/efuns/set_living_name.c \
../testsuite/single/tests/efuns/set_privs.c \
../testsuite/single/tests/efuns/shadow.c \
../testsuite/single/tests/efuns/shutdown.c \
../testsuite/single/tests/efuns/sizeof.c \
../testsuite/single/tests/efuns/snoop.c \
../testsuite/single/tests/efuns/sprintf.c \
../testsuite/single/tests/efuns/sscanf.c \
../testsuite/single/tests/efuns/talker.c \
../testsuite/single/tests/efuns/to_float.c \
../testsuite/single/tests/efuns/to_int.c \
../testsuite/single/tests/efuns/unloaded.c \
../testsuite/single/tests/efuns/users.c \
../testsuite/single/tests/efuns/values.c 

OBJS += \
./testsuite/single/tests/efuns/add_action.o \
./testsuite/single/tests/efuns/add_light.o \
./testsuite/single/tests/efuns/all_inventory.o \
./testsuite/single/tests/efuns/allocate.o \
./testsuite/single/tests/efuns/allocate_buffer.o \
./testsuite/single/tests/efuns/allocate_mapping.o \
./testsuite/single/tests/efuns/badshad.o \
./testsuite/single/tests/efuns/bind.o \
./testsuite/single/tests/efuns/break_string.o \
./testsuite/single/tests/efuns/cache_stats.o \
./testsuite/single/tests/efuns/call_other.o \
./testsuite/single/tests/efuns/call_out.o \
./testsuite/single/tests/efuns/call_stack.o \
./testsuite/single/tests/efuns/capitalize.o \
./testsuite/single/tests/efuns/children.o \
./testsuite/single/tests/efuns/clear_bit.o \
./testsuite/single/tests/efuns/clone_object.o \
./testsuite/single/tests/efuns/clonep.o \
./testsuite/single/tests/efuns/command.o \
./testsuite/single/tests/efuns/cp.o \
./testsuite/single/tests/efuns/crc32.o \
./testsuite/single/tests/efuns/ctime.o \
./testsuite/single/tests/efuns/deep_inherit_list.o \
./testsuite/single/tests/efuns/deep_inventory.o \
./testsuite/single/tests/efuns/destruct.o \
./testsuite/single/tests/efuns/disable_commands.o \
./testsuite/single/tests/efuns/dumpallobj.o \
./testsuite/single/tests/efuns/ed.o \
./testsuite/single/tests/efuns/enable_wizard.o \
./testsuite/single/tests/efuns/environment.o \
./testsuite/single/tests/efuns/error.o \
./testsuite/single/tests/efuns/exec.o \
./testsuite/single/tests/efuns/explode.o \
./testsuite/single/tests/efuns/file_name.o \
./testsuite/single/tests/efuns/file_size.o \
./testsuite/single/tests/efuns/filter.o \
./testsuite/single/tests/efuns/find_call_out.o \
./testsuite/single/tests/efuns/find_living.o \
./testsuite/single/tests/efuns/find_object.o \
./testsuite/single/tests/efuns/find_player.o \
./testsuite/single/tests/efuns/function_exists.o \
./testsuite/single/tests/efuns/function_profile.o \
./testsuite/single/tests/efuns/functionp.o \
./testsuite/single/tests/efuns/generate_source.o \
./testsuite/single/tests/efuns/get_char.o \
./testsuite/single/tests/efuns/get_config.o \
./testsuite/single/tests/efuns/get_dir.o \
./testsuite/single/tests/efuns/goodshad.o \
./testsuite/single/tests/efuns/has_errors.o \
./testsuite/single/tests/efuns/implode.o \
./testsuite/single/tests/efuns/in_edit.o \
./testsuite/single/tests/efuns/inh0.o \
./testsuite/single/tests/efuns/inh1.o \
./testsuite/single/tests/efuns/inh2.o \
./testsuite/single/tests/efuns/inherit_list.o \
./testsuite/single/tests/efuns/inherits.o \
./testsuite/single/tests/efuns/input_to.o \
./testsuite/single/tests/efuns/interactive.o \
./testsuite/single/tests/efuns/intp.o \
./testsuite/single/tests/efuns/keys.o \
./testsuite/single/tests/efuns/light.o \
./testsuite/single/tests/efuns/living.o \
./testsuite/single/tests/efuns/livings.o \
./testsuite/single/tests/efuns/lower_case.o \
./testsuite/single/tests/efuns/malloc_status.o \
./testsuite/single/tests/efuns/map.o \
./testsuite/single/tests/efuns/map_delete.o \
./testsuite/single/tests/efuns/mapp.o \
./testsuite/single/tests/efuns/master.o \
./testsuite/single/tests/efuns/match_path.o \
./testsuite/single/tests/efuns/member_array.o \
./testsuite/single/tests/efuns/message.o \
./testsuite/single/tests/efuns/mkdir.o \
./testsuite/single/tests/efuns/move_object.o \
./testsuite/single/tests/efuns/mud_status.o \
./testsuite/single/tests/efuns/notify_fail.o \
./testsuite/single/tests/efuns/nullp.o \
./testsuite/single/tests/efuns/objectp.o \
./testsuite/single/tests/efuns/opcprof.o \
./testsuite/single/tests/efuns/origin.o \
./testsuite/single/tests/efuns/pointerp.o \
./testsuite/single/tests/efuns/present.o \
./testsuite/single/tests/efuns/previous_object.o \
./testsuite/single/tests/efuns/printf.o \
./testsuite/single/tests/efuns/query_ed_mode.o \
./testsuite/single/tests/efuns/query_idle.o \
./testsuite/single/tests/efuns/query_ip_name.o \
./testsuite/single/tests/efuns/query_ip_number.o \
./testsuite/single/tests/efuns/query_load_average.o \
./testsuite/single/tests/efuns/query_privs.o \
./testsuite/single/tests/efuns/query_snoop.o \
./testsuite/single/tests/efuns/query_snooping.o \
./testsuite/single/tests/efuns/query_verb.o \
./testsuite/single/tests/efuns/random.o \
./testsuite/single/tests/efuns/read_buffer.o \
./testsuite/single/tests/efuns/read_bytes.o \
./testsuite/single/tests/efuns/read_file.o \
./testsuite/single/tests/efuns/receive.o \
./testsuite/single/tests/efuns/reg_assoc.o \
./testsuite/single/tests/efuns/regexp.o \
./testsuite/single/tests/efuns/remove_action.o \
./testsuite/single/tests/efuns/remove_call_out.o \
./testsuite/single/tests/efuns/rename.o \
./testsuite/single/tests/efuns/replace_string.o \
./testsuite/single/tests/efuns/restore_object.o \
./testsuite/single/tests/efuns/restore_variable.o \
./testsuite/single/tests/efuns/rm.o \
./testsuite/single/tests/efuns/rmdir.o \
./testsuite/single/tests/efuns/save_object.o \
./testsuite/single/tests/efuns/save_variable.o \
./testsuite/single/tests/efuns/say.o \
./testsuite/single/tests/efuns/set_bit.o \
./testsuite/single/tests/efuns/set_debug_level.o \
./testsuite/single/tests/efuns/set_heart_beat.o \
./testsuite/single/tests/efuns/set_hide.o \
./testsuite/single/tests/efuns/set_light.o \
./testsuite/single/tests/efuns/set_living_name.o \
./testsuite/single/tests/efuns/set_privs.o \
./testsuite/single/tests/efuns/shadow.o \
./testsuite/single/tests/efuns/shutdown.o \
./testsuite/single/tests/efuns/sizeof.o \
./testsuite/single/tests/efuns/snoop.o \
./testsuite/single/tests/efuns/sprintf.o \
./testsuite/single/tests/efuns/sscanf.o \
./testsuite/single/tests/efuns/talker.o \
./testsuite/single/tests/efuns/to_float.o \
./testsuite/single/tests/efuns/to_int.o \
./testsuite/single/tests/efuns/unloaded.o \
./testsuite/single/tests/efuns/users.o \
./testsuite/single/tests/efuns/values.o 

C_DEPS += \
./testsuite/single/tests/efuns/add_action.d \
./testsuite/single/tests/efuns/add_light.d \
./testsuite/single/tests/efuns/all_inventory.d \
./testsuite/single/tests/efuns/allocate.d \
./testsuite/single/tests/efuns/allocate_buffer.d \
./testsuite/single/tests/efuns/allocate_mapping.d \
./testsuite/single/tests/efuns/badshad.d \
./testsuite/single/tests/efuns/bind.d \
./testsuite/single/tests/efuns/break_string.d \
./testsuite/single/tests/efuns/cache_stats.d \
./testsuite/single/tests/efuns/call_other.d \
./testsuite/single/tests/efuns/call_out.d \
./testsuite/single/tests/efuns/call_stack.d \
./testsuite/single/tests/efuns/capitalize.d \
./testsuite/single/tests/efuns/children.d \
./testsuite/single/tests/efuns/clear_bit.d \
./testsuite/single/tests/efuns/clone_object.d \
./testsuite/single/tests/efuns/clonep.d \
./testsuite/single/tests/efuns/command.d \
./testsuite/single/tests/efuns/cp.d \
./testsuite/single/tests/efuns/crc32.d \
./testsuite/single/tests/efuns/ctime.d \
./testsuite/single/tests/efuns/deep_inherit_list.d \
./testsuite/single/tests/efuns/deep_inventory.d \
./testsuite/single/tests/efuns/destruct.d \
./testsuite/single/tests/efuns/disable_commands.d \
./testsuite/single/tests/efuns/dumpallobj.d \
./testsuite/single/tests/efuns/ed.d \
./testsuite/single/tests/efuns/enable_wizard.d \
./testsuite/single/tests/efuns/environment.d \
./testsuite/single/tests/efuns/error.d \
./testsuite/single/tests/efuns/exec.d \
./testsuite/single/tests/efuns/explode.d \
./testsuite/single/tests/efuns/file_name.d \
./testsuite/single/tests/efuns/file_size.d \
./testsuite/single/tests/efuns/filter.d \
./testsuite/single/tests/efuns/find_call_out.d \
./testsuite/single/tests/efuns/find_living.d \
./testsuite/single/tests/efuns/find_object.d \
./testsuite/single/tests/efuns/find_player.d \
./testsuite/single/tests/efuns/function_exists.d \
./testsuite/single/tests/efuns/function_profile.d \
./testsuite/single/tests/efuns/functionp.d \
./testsuite/single/tests/efuns/generate_source.d \
./testsuite/single/tests/efuns/get_char.d \
./testsuite/single/tests/efuns/get_config.d \
./testsuite/single/tests/efuns/get_dir.d \
./testsuite/single/tests/efuns/goodshad.d \
./testsuite/single/tests/efuns/has_errors.d \
./testsuite/single/tests/efuns/implode.d \
./testsuite/single/tests/efuns/in_edit.d \
./testsuite/single/tests/efuns/inh0.d \
./testsuite/single/tests/efuns/inh1.d \
./testsuite/single/tests/efuns/inh2.d \
./testsuite/single/tests/efuns/inherit_list.d \
./testsuite/single/tests/efuns/inherits.d \
./testsuite/single/tests/efuns/input_to.d \
./testsuite/single/tests/efuns/interactive.d \
./testsuite/single/tests/efuns/intp.d \
./testsuite/single/tests/efuns/keys.d \
./testsuite/single/tests/efuns/light.d \
./testsuite/single/tests/efuns/living.d \
./testsuite/single/tests/efuns/livings.d \
./testsuite/single/tests/efuns/lower_case.d \
./testsuite/single/tests/efuns/malloc_status.d \
./testsuite/single/tests/efuns/map.d \
./testsuite/single/tests/efuns/map_delete.d \
./testsuite/single/tests/efuns/mapp.d \
./testsuite/single/tests/efuns/master.d \
./testsuite/single/tests/efuns/match_path.d \
./testsuite/single/tests/efuns/member_array.d \
./testsuite/single/tests/efuns/message.d \
./testsuite/single/tests/efuns/mkdir.d \
./testsuite/single/tests/efuns/move_object.d \
./testsuite/single/tests/efuns/mud_status.d \
./testsuite/single/tests/efuns/notify_fail.d \
./testsuite/single/tests/efuns/nullp.d \
./testsuite/single/tests/efuns/objectp.d \
./testsuite/single/tests/efuns/opcprof.d \
./testsuite/single/tests/efuns/origin.d \
./testsuite/single/tests/efuns/pointerp.d \
./testsuite/single/tests/efuns/present.d \
./testsuite/single/tests/efuns/previous_object.d \
./testsuite/single/tests/efuns/printf.d \
./testsuite/single/tests/efuns/query_ed_mode.d \
./testsuite/single/tests/efuns/query_idle.d \
./testsuite/single/tests/efuns/query_ip_name.d \
./testsuite/single/tests/efuns/query_ip_number.d \
./testsuite/single/tests/efuns/query_load_average.d \
./testsuite/single/tests/efuns/query_privs.d \
./testsuite/single/tests/efuns/query_snoop.d \
./testsuite/single/tests/efuns/query_snooping.d \
./testsuite/single/tests/efuns/query_verb.d \
./testsuite/single/tests/efuns/random.d \
./testsuite/single/tests/efuns/read_buffer.d \
./testsuite/single/tests/efuns/read_bytes.d \
./testsuite/single/tests/efuns/read_file.d \
./testsuite/single/tests/efuns/receive.d \
./testsuite/single/tests/efuns/reg_assoc.d \
./testsuite/single/tests/efuns/regexp.d \
./testsuite/single/tests/efuns/remove_action.d \
./testsuite/single/tests/efuns/remove_call_out.d \
./testsuite/single/tests/efuns/rename.d \
./testsuite/single/tests/efuns/replace_string.d \
./testsuite/single/tests/efuns/restore_object.d \
./testsuite/single/tests/efuns/restore_variable.d \
./testsuite/single/tests/efuns/rm.d \
./testsuite/single/tests/efuns/rmdir.d \
./testsuite/single/tests/efuns/save_object.d \
./testsuite/single/tests/efuns/save_variable.d \
./testsuite/single/tests/efuns/say.d \
./testsuite/single/tests/efuns/set_bit.d \
./testsuite/single/tests/efuns/set_debug_level.d \
./testsuite/single/tests/efuns/set_heart_beat.d \
./testsuite/single/tests/efuns/set_hide.d \
./testsuite/single/tests/efuns/set_light.d \
./testsuite/single/tests/efuns/set_living_name.d \
./testsuite/single/tests/efuns/set_privs.d \
./testsuite/single/tests/efuns/shadow.d \
./testsuite/single/tests/efuns/shutdown.d \
./testsuite/single/tests/efuns/sizeof.d \
./testsuite/single/tests/efuns/snoop.d \
./testsuite/single/tests/efuns/sprintf.d \
./testsuite/single/tests/efuns/sscanf.d \
./testsuite/single/tests/efuns/talker.d \
./testsuite/single/tests/efuns/to_float.d \
./testsuite/single/tests/efuns/to_int.d \
./testsuite/single/tests/efuns/unloaded.d \
./testsuite/single/tests/efuns/users.d \
./testsuite/single/tests/efuns/values.d 


# Each subdirectory must supply rules for building sources it contributes
testsuite/single/tests/efuns/%.o: ../testsuite/single/tests/efuns/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


